# Generated by Django 4.2.6 on 2023-10-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("icecreamapi", "0003_earnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="earnings",
            field=models.ForeignKey(
                default=0.0,
                on_delete=django.db.models.deletion.CASCADE,
                to="icecreamapi.earnings",
            ),
            preserve_default=False,
        ),
    ]
